#!/bin/bash

user_agent="Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"
base_url="http://musicbrainz.org/ws/2"
entity="artist"
id="83d91898-7763-47d7-b03b-b92132375c47"
format="json"

wget -U "${user_agent}" -qO- "${base_url}/${entity}/${id}?fmt=json"
